### ISSUE TITLE
LLchisq() not an available function

### ISSUE THREAD

**Issue by rburstein-IDM** [jslefche/sem_book#3]
Hi! In Chapter 3.4 you go over the Log-Likelihood chi-squared test and make reference to a function `LLchisq()` , which I presume should be in your `piecewiseSEM` package, but I don't see it in there (or in any other R package) and am not able to run it. Very nice book by the way, thanks for this resource!

**Comment by jslefche** [comment]
Cheers, thanks for that. You need to install the development version of piecewise:

`devtools::install_github(“jslefche/piecewiseSEM@devel”)`

Recognize that there are probably still lots of bugs lurking in there, so if you find one, please file an issue…thanks!

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
